# .github/workflows/duyuru_kontrol.yml

name: Maltepe Duyuru Kontrol

on:
  schedule:
    - cron: '0 7 * * 1-5'
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  check-announcements:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'MAU Duyuru'

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python'u Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Bağımlılıkları Yükle
        run: pip install -r requirements.txt

      - name: Duyuru Takip Script'ini Çalıştır
        env:
          EMAIL_ENABLED: ${{ secrets.EMAIL_ENABLED }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        run: python MAU_Duyuru.py
      
      # --- YENİ KANIT TOPLAMA ADIMI ---
      # Bu adım SADECE bir önceki adım hata verirse çalışır.
      # Oluşturulan debug_page.html dosyasını indirilebilir bir ürün haline getirir.
      - name: Debug Dosyasını Kaydet (Hata Durumunda)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: debug-kanit-dosyasi
          path: MAU Duyuru/debug_page.html
