# İş akışının adı
name: Maltepe Duyuru Kontrol

on:
  schedule:
    # Hafta içi her gün saat 10:00 (Türkiye saati) için cron zamanlaması
    - cron: '0 7 * * 1-5'

   # --- YENİ EKLENDİ: Akşam 17:00 kontrolü ---
    # Her gün saat 17:00 (Türkiye saati) için yeni cron zamanlaması. 17:00 (UTC+3) -> 14:00 (UTC)
    - cron: '0 14 * * *'
    
  workflow_dispatch:
  push:
    branches:
      - main
      - master

# --- YENİ EKLENDİ: İŞ AKIŞINA YAZMA İZNİ VERME ---
# Bu bölüm, iş akışının deponuza dosya gönderebilmesi için gereklidir.
permissions:
  contents: write

jobs:
  check-announcements:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'MAU Duyuru'

    steps:
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      - name: Python'u Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Bağımlılıkları Yükle
        run: pip install -r requirements.txt

      - name: Duyuru Takip Script'ini Çalıştır
        env:
          EMAIL_ENABLED: ${{ secrets.EMAIL_ENABLED }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        run: python MAU_Duyuru.py
      
      # --- YENİ EKLENDİ: GÜNCELLENEN DOSYAYI GITHUB'A GÖNDERME ---
      - name: Güncel Duyuru Listesini Geri Yükle
        run: |
          # Git için bot kimliğini yapılandır
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          # working-directory ayarı nedeniyle dosya yolu sadeleştirildi
          if [[ -n $(git status --porcelain last_announcements.json) ]]; then
            echo "last_announcements.json dosyasında değişiklikler algılandı. Geri yükleniyor..."
            
            # 1. Önce yerel değişikliği ekle ve commit'le
            git add last_announcements.json
            git commit -m "Duyuru listesi güncellendi [skip ci]"
            
            # 2. Şimdi uzak depodaki değişiklikleri çek
            git pull --rebase
            
            # 3. Son olarak birleştirilmiş halini uzak depoya gönder
            git push
          else
            echo "last_announcements.json dosyasında değişiklik yok."
          fi
