# İş akışının adı
name: Maltepe Duyuru Kontrol

on:
  schedule:
    # Hafta içi her gün saat 10:00 (Türkiye saati) için cron zamanlaması
    # NOT: GitHub Actions UTC saat dilimini kullanır. 10:00 (UTC+3) -> 07:00 (UTC)
    - cron: '0 7 * * 1-5'
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  check-announcements:
    runs-on: ubuntu-latest
    
    # --- EKLENEN SATIRLAR ---
    # Bu görevdeki tüm adımların hangi klasörde çalışacağını belirler
    defaults:
      run:
        working-directory: 'MAU Duyuru'

    steps:
      # 1. Adım: Kodu GitHub deposundan sanal makineye indirir
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      # 2. Adım: Python'u kurar
      - name: Python'u Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3. Adım: Gerekli Python kütüphanelerini yükler
      # Artık doğru klasörde olduğu için dosyayı bulacaktır
      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Adım: Python script'ini çalıştırır
      - name: Duyuru Takip Script'ini Çalıştır
        env:
          EMAIL_ENABLED: ${{ secrets.EMAIL_ENABLED }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        run: python MAU_Duyuru.py
