# İş akışının adı
name: Maltepe Duyuru Kontrol

# Bu iş akışını neyin tetikleyeceğini belirler
on:
  schedule:
    # Hafta içi her gün saat 10:00 (Türkiye saati) için cron zamanlaması
    # NOT: GitHub Actions UTC saat dilimini kullanır. 10:00 (UTC+3) -> 07:00 (UTC)
    - cron: '0 7 * * 1-5'
  workflow_dispatch:
  push:
    branches:
      - main
      - master

# İş akışında çalışacak görevler
jobs:
  check-announcements:
    runs-on: ubuntu-latest
    steps:
      # 1. Adım: Kodu GitHub deposundan sanal makineye indirir
      - name: Depoyu Klonla
        uses: actions/checkout@v4

      # 2. Adım: Python'u kurar
      - name: Python'u Kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # --- YENİ HATA AYIKLAMA ADIMI ---
      # Bu adım, mevcut klasördeki tüm dosyaları ve klasörleri listeleyerek
      # requirements.txt dosyasının nerede olduğunu görmemizi sağlar.
      - name: Dosyaları Listele (Hata Ayıklama)
        run: ls -lR

      # 3. Adım: Gerekli Python kütüphanelerini yükler
      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Adım: Python script'ini çalıştırır
      - name: Duyuru Takip Script'ini Çalıştır
        env:
          EMAIL_ENABLED: ${{ secrets.EMAIL_ENABLED }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          NOTIFICATION_EMAIL: ${{ secrets.NOTIFICATION_EMAIL }}
        # --- DÜZELTME: Script adı doğru isimle değiştirildi ---
        run: python MAU_Duyuru.py
